# Java Gradle CircleCI 2.1 configuration file
version: 2.1
description: |
    Simplify common tasks for building and testing Java projects using Gradle.
display:
    home_url: https://gradle.org/
    source_url: https://github.com/CircleCI-Public/gradle-orb
orbs:
  gradle: circleci/gradle@3.0.0
jobs:
  say_workflow_starting:
    docker:
      - image: cimg/openjdk:18.0.1
      # - image: cimg/base:stable
    steps:
      - run: echo "CircleCI Workflow starting"
  say_workflow_ending:
    docker:
      - image: cimg/openjdk:18.0.1
      # - image: cimg/base:stable
    steps:
      - run: echo "CircleCI Workflow ending."
  build:
    docker:
      - image: cimg/openjdk:18.0.1
    steps:
      - checkout
      - run: java --version
  checkout-build-test:
      docker:
        - image: cimg/openjdk:18.0.1
      steps:
        - checkout
        - run: java --version
        - gradle/test
workflows:
    # Name of workflow
  run_jobs:
    # List of jobs that will run
    jobs:
      - say_workflow_starting
      - build
      - say_workflow_ending
