# Java Gradle CircleCI 2.1 configuration file
version: 2.1
description: |
    Simplify common tasks for building and testing Java projects using Gradle.
display:
    home_url: https://gradle.org/
    source_url: https://github.com/CircleCI-Public/gradle-orb
orbs:
  gradle: circleci/gradle@3.0.0
jobs:
    # Job one with a unique name
  say_hello:
    docker:
      # - image: circleci/openjdk:8-jdk
      - image: cimg/openjdk:18.0.1
      # - image: cimg/base:stable
    steps:
      - run: echo "Say hello to YAML!"
  build:
    docker:
      - image: cimg/openjdk:18.0.1
    steps:
      - checkout
      - run: java --version
workflows:
    # Name of workflow
  run_jobs:
    # List of jobs that will run
    jobs:
      - say_hello
      - build
      # - say_goodbye
    # checkout-build-test:
    #     jobs:
    #         - gradle/test